<?php 
/**
 * Implements hook_block_info().
 */
function file_to_form_converter_block_info() {
  $blocks = array();
  $blocks['file_to_block'] = array(
    'info' => t('File To Form Converter'),
	    /*'status' => 1,
	    'region' => 'content',*/
	    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function file_to_form_converter_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case '':
      $block['subject'] = t('');
      $block['content'] = file_to_form_result();
      break;
  }
  return $block;
}

/**
 * Implements file_to_form_result().
 */
function file_to_form_converter_result() {
  return theme('file_to_form_result');
}


/*
 * Implement hook_theme().
 */
function file_to_form_converter_theme(){
  $templates = array(
    'file_to_form_result' => array(
      'template' => '/templates/file-to-form-result-template',
    ),
  );
  return $templates;
}
/**
 * Implements hook_preprocess_block().
 */
/*function file_to_form_converter_preprocess_block(&$variables) {
  if ($variables['block']->bid === 'target_block_id') {
  
  } 
  else if ($variables['block']->bid === 'other_target_block_id') {
  
  }
}*/
?>